"""empty message

Revision ID: b76f50afb86e
Revises: dbc581a2a414
Create Date: 2023-07-07 09:25:59.518020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76f50afb86e'
down_revision = 'dbc581a2a414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('service_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('date', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'appointments', 'services', ['service_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'date')
    op.drop_column('appointments', 'service_id')
    # ### end Alembic commands ###
